pet/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CategoryViewSet, ReviewViewSet, StudyViewSet

app_name = 'api'


v1_router = DefaultRouter()
v1_router.register(
    'study',
    StudyViewSet,
    basename='study'
)
v1_router.register(
    'category',
    CategoryViewSet,
    basename='category'
)
v1_router.register(
    r'study/(?P<study_id>\d+)/review',
    ReviewViewSet,
    basename='review'
)
urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('v1/', include(v1_router.urls))
]

pet/pet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from study import views
from study.forms import CustomUserForm

handler404 = 'tools.views.page_not_found'
handler500 = 'tools.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/logout/',
         views.CustomLogoutView.as_view(),
         name='custom_logout'),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration.html',
            form_class=CustomUserForm,
            success_url=reverse_lazy('study:list')
        ),
        name='registration'
    ),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('project_tools/', include('tools.urls', namespace='tools')),
    path('', include('study.urls', namespace='study')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/profiles/urls.py
from django.urls import path

from .views import ProfileDetailView, ProfileListView

app_name = 'profiles'


urlpatterns = [
    path('list/',
         ProfileListView.as_view(),
         name='list'),
    path('detail/<slug:username>/',
         ProfileDetailView.as_view(),
         name='detail')
]

pet/study/urls.py
from django.urls import path

from . import views


app_name = 'study'


urlpatterns = [
     path('',
          views.StudyListView.as_view(),
          name='list'),
    path('study/create/',
         views.StudyCreateView.as_view(),
         name='create'),
    path('study/detail/<int:study_id>/add_documents/',
         views.add_documents_for_study,
         name='download_documents'),
    path('study/detail/<int:study_id>/',
         views.StudyDetailView.as_view(),
         name='detail'),
    path('study/update/<int:study_id>/',
         views.StudyUpdateView.as_view(),
         name='update'),
    path('study/delete/<int:study_id>/',
         views.StudyDeleteView.as_view(),
         name='delete'),
    path('study/<int:study_id>/review/create/',
         views.ReviewCreateView.as_view(),
         name='review_create'),
    path('study/<int:study_id>/review/update/<int:review_id>/',
         views.ReviewUpdateView.as_view(),
         name='review_update'),
    path('study/<int:study_id>/review/delete/<int:review_id>/',
         views.ReviewDeleteView.as_view(),
         name='review_delete'),
    path('category/list/',
         views.CategoryListView.as_view(),
         name='category_list'),
    path('category/create/',
         views.CategoryCreateView.as_view(),
         name='category_create'),
    path('category/detail/<slug:category_slug>/',
         views.CategoryDetailView.as_view(),
         name='category_detail'),
    path('category/update/<slug:category_slug>/',
         views.CategoryUpdateView.as_view(),
         name='category_update'),
    path('category/delete/<slug:category_slug>/',
         views.CategoryDeleteView.as_view(),
         name='category_delete'),
]

pet/profiles/models.py
from django.db import models

# Create your models here.

pet/profiles/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView

from study.models import CustomUser, Study
from study.project_tools import (add_review_info_for_study, filtered_queryset,
                                 get_page_object)


class ProfileListView(ListView, LoginRequiredMixin):
    model = CustomUser
    paginate_by = 4
    template_name = 'profiles/list.html'


class ProfileDetailView(DetailView, LoginRequiredMixin):
    model = CustomUser
    template_name = 'profiles/detail.html'
    slug_url_kwarg = 'username'
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **kwargs,
            page_obj=get_page_object(
                add_review_info_for_study(filtered_queryset(Study.objects)),
                settings.STUDY_COUNT_ON_LIST_PAGE,
                self.request.GET.get('page')
            ),
            categories=filtered_queryset(
                self.get_object().categories.all()
            )
        )

pet/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
  Преподаватели
{% endblock %}

{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card col-5 m-5">
      <div class="card-body">
          <h1 class="card-header text-center">{{ object.username }}</h1>
          <p class="card-text m-3">
            Фамилия: {{ object.first_name }}<br>
            Имя: {{ object.last_name }}<br>
            Почта: {{ object.email }}
          </p>
      </div>
    </div>
  </div>
  <hr>
  <h3 class="text-info text-center">Материалы преподавателя {{ object.username }}</h3><br>
  <div class="col d-flex justify-content-center">
    {% if not categories %}
      <span class="text-warning fs-4">Преподаватель {{ object.username }} не представлен в категориях</span>
    {% else %}
      <ul class="col-5 list-group">
        <li class="list-group-item active">Из категорий</li>
        {% for category in categories %}
          <li class="list-group-item">
            <a href="{% url 'study:category_detail' category.slug %}" class="btn btm-sm text-primary">{{ category.name }}</a>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
  <hr>
  <div class="row mx-auto">
    <p>
      {% for study in page_obj %}
        {% include 'includes/study_card.html' %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </p>
  </div>
{% endblock %}

pet/templates/profiles/list.html
{% extends 'base.html' %}

{% block title %}
  Преподаватели
{% endblock %}

{% block content %}
  <div class="row mx-auto">
    {% for profile in page_obj %}
      {% include 'includes/profile_card.html' %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}