pet/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CategoryViewSet, ReviewViewSet, StudyViewSet

app_name = 'api'


v1_router = DefaultRouter()
v1_router.register(
    'study',
    StudyViewSet,
    basename='study'
)
v1_router.register(
    'category',
    CategoryViewSet,
    basename='category'
)
v1_router.register(
    r'study/(?P<study_id>\d+)/review',
    ReviewViewSet,
    basename='review'
)
urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('v1/', include(v1_router.urls))
]

pet/pet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from study import views
from study.forms import CustomUserForm

handler404 = 'tools.views.page_not_found'
handler500 = 'tools.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/logout/',
         views.CustomLogoutView.as_view(),
         name='custom_logout'),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration.html',
            form_class=CustomUserForm,
            success_url=reverse_lazy('study:list')
        ),
        name='registration'
    ),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('project_tools/', include('tools.urls', namespace='tools')),
    path('', include('study.urls', namespace='study')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/study/urls.py
from django.urls import path

from . import views


app_name = 'study'


urlpatterns = [
     path('',
          views.StudyListView.as_view(),
          name='list'),
    path('study/create/',
         views.StudyCreateView.as_view(),
         name='create'),
    path('study/detail/<int:study_id>/add_documents/',
         views.add_documents_for_study,
         name='download_documents'),
    path('study/detail/<int:study_id>/',
         views.StudyDetailView.as_view(),
         name='detail'),
    path('study/update/<int:study_id>/',
         views.StudyUpdateView.as_view(),
         name='update'),
    path('study/delete/<int:study_id>/',
         views.StudyDeleteView.as_view(),
         name='delete'),
    path('study/<int:study_id>/review/create/',
         views.ReviewCreateView.as_view(),
         name='review_create'),
    path('study/<int:study_id>/review/update/<int:review_id>/',
         views.ReviewUpdateView.as_view(),
         name='review_update'),
    path('study/<int:study_id>/review/delete/<int:review_id>/',
         views.ReviewDeleteView.as_view(),
         name='review_delete'),
    path('category/list/',
         views.CategoryListView.as_view(),
         name='category_list'),
    path('category/create/',
         views.CategoryCreateView.as_view(),
         name='category_create'),
    path('category/detail/<slug:category_slug>/',
         views.CategoryDetailView.as_view(),
         name='category_detail'),
    path('category/update/<slug:category_slug>/',
         views.CategoryUpdateView.as_view(),
         name='category_update'),
    path('category/delete/<slug:category_slug>/',
         views.CategoryDeleteView.as_view(),
         name='category_delete'),
]

pet/tools/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'tools'


urlpatterns = [
    path('about/',
         TemplateView.as_view(template_name='tools/about.html'),
         name='about'),
    path('rules/',
         TemplateView.as_view(template_name='tools/rules.html'),
         name='rules'),
]

pet/tools/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'tools/404.html', status=404)


def server_error(request):
    return render(request, 'tools/500.html', status=500)


def csrf_failure(request, reason=''):
    return render(request, 'tools/403_csrf_failure.html', status=403)

pet/templates/tools/403_csrf_status.html
{% extends 'base.html' %}

{% block title %}
  Ошибка 403
{% endblock %}

{% block content %}
  <div class="card col-6 m-5">
    <h1 class="card-header text-danger">
      Ошибка CSRF - 403
    </h1>
    <div class="card-body">
      <p>Ошибка отправки данных! {{ request.path }}</p>
      <p><a href="{% url 'study:list' %}">Вернуться на главную</a></p>
    </div>
  </div>
{% endblock %}

pet/templates/tools/about.html
{% extends 'base.html' %}

{% block title %}
  О KARTStudy
{% endblock %}

{% block content %}
  <div class="col-7 m-3 fs-5">
    <span class="fs-1">KARTStudy</span> - это образовательная среда, с множеством различных категорий предметов на выбор.<br><hr>
    Здесь можно найти курсы по определенному разделу или записаться на полноценные занятия с преподователем.<br>
    <ul>
      <li><a href="{% url 'profiles:list' %}" class="btn btn-info my-2">Преподаватели</a></li>
      <li><a href="{% url 'study:list' %}" class="btn btn-info my-2">Курсы</a></li>
    </ul>
  </div>
{% endblock %}

pet/templates/tools/rules.html
{% extends 'base.html' %}

{% block title %}
  Правила
{% endblock %}

{% block content %}
  <div class="col d-flex justify-content-center">
    <p class="text-danger fs-4 m-5">
      Правила ещё в разработке!
    </p>
  </div>
{% endblock %}