pet/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CategoryViewSet, ReviewViewSet, StudyViewSet

app_name = 'api'


v1_router = DefaultRouter()
v1_router.register(
    'study',
    StudyViewSet,
    basename='study'
)
v1_router.register(
    'category',
    CategoryViewSet,
    basename='category'
)
v1_router.register(
    r'study/(?P<study_id>\d+)/review',
    ReviewViewSet,
    basename='review'
)
urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('v1/', include(v1_router.urls))
]

pet/pet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from study import views
from study.forms import CustomUserForm

handler404 = 'tools.views.page_not_found'
handler500 = 'tools.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/logout/',
         views.CustomLogoutView.as_view(),
         name='custom_logout'),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration.html',
            form_class=CustomUserForm,
            success_url=reverse_lazy('study:list')
        ),
        name='registration'
    ),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('project_tools/', include('tools.urls', namespace='tools')),
    path('', include('study.urls', namespace='study')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/study/urls.py
from django.urls import path

from . import views


app_name = 'study'


urlpatterns = [
     path('',
          views.StudyListView.as_view(),
          name='list'),
    path('study/create/',
         views.StudyCreateView.as_view(),
         name='create'),
    path('study/detail/<int:study_id>/add_documents/',
         views.add_documents_for_study,
         name='download_documents'),
    path('study/detail/<int:study_id>/',
         views.StudyDetailView.as_view(),
         name='detail'),
    path('study/update/<int:study_id>/',
         views.StudyUpdateView.as_view(),
         name='update'),
    path('study/delete/<int:study_id>/',
         views.StudyDeleteView.as_view(),
         name='delete'),
    path('study/<int:study_id>/review/create/',
         views.ReviewCreateView.as_view(),
         name='review_create'),
    path('study/<int:study_id>/review/update/<int:review_id>/',
         views.ReviewUpdateView.as_view(),
         name='review_update'),
    path('study/<int:study_id>/review/delete/<int:review_id>/',
         views.ReviewDeleteView.as_view(),
         name='review_delete'),
    path('category/list/',
         views.CategoryListView.as_view(),
         name='category_list'),
    path('category/create/',
         views.CategoryCreateView.as_view(),
         name='category_create'),
    path('category/detail/<slug:category_slug>/',
         views.CategoryDetailView.as_view(),
         name='category_detail'),
    path('category/update/<slug:category_slug>/',
         views.CategoryUpdateView.as_view(),
         name='category_update'),
    path('category/delete/<slug:category_slug>/',
         views.CategoryDeleteView.as_view(),
         name='category_delete'),
]

pet/study/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Category, CustomUser, Document, Review, Study


class StudyForm(forms.ModelForm):
    class Meta:
        model = Study
        exclude = ['author']


class CategoryForm(forms.ModelForm):
    class Meta:
        exclude = ['author']
        model = Category


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['author', 'study', 'edited']


class CustomUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = '__all__'

pet/study/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from .forms import CategoryForm, DocumentForm, StudyForm
from .mixins import (CategoryChangeMixin, CategoryFormMixin, CategoryMixin,
                     OnlyAuthorMixin, OnlyStaffCanChange,
                     OnlyTeacherAuthorMixin, ReviewFormMixin, ReviewModelMixin,
                     ReviewURLParamMixin, StudyChangeMixin, StudyFormMixin,
                     StudyMixin)
from .models import Category, Document, Study
from .project_tools import (add_review_info_for_study, filtered_queryset,
                            get_page_object, get_study_avg_rating)


class CustomLogoutView(
    LogoutView
):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class StudyListView(
    StudyMixin, ListView
):
    template_name = 'study/list.html'

    def get_queryset(self):
        user = self.request.user
        status = None
        if user.is_authenticated:
            status = user.status
        return filtered_queryset(
            self.model.objects, is_admin=user.is_staff,
            teacher=status
        )

    def get_context_data(self, *args, **kwargs):
        return super().get_context_data(
            **kwargs,
            page_obj=get_page_object(
                add_review_info_for_study(self.get_queryset()),
                settings.STUDY_COUNT_ON_LIST_PAGE,
                self.request.GET.get('page')
            )
        )


class StudyCreateView(
    StudyChangeMixin, StudyFormMixin, OnlyTeacherAuthorMixin, CreateView
):
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class StudyUpdateView(
    StudyChangeMixin, StudyFormMixin, OnlyTeacherAuthorMixin, UpdateView
):
    pass


class StudyDetailView(
    StudyChangeMixin, DetailView
):
    template_name = 'study/detail.html'

    def dispatch(self, request, *args, **kwargs):
        if (request.user == self.get_object().author
            or (self.get_object().is_published
                and self.get_object().is_on_main)):
            return super().dispatch(request, *args, **kwargs)
        return redirect('study:list')

    def get_context_data(self, **kwargs):
        study = get_object_or_404(
            Study,
            pk=self.kwargs[self.pk_url_kwarg]
        )
        study.avg_rating = get_study_avg_rating(study)
        return super().get_context_data(
            **kwargs,
            study=study,
            page_obj=get_page_object(
                self.get_object().reviews.all(),
                settings.REVIEW_COUNT_ON_DETAIL_STUDY_PAGE,
                self.request.GET.get('page')
            )
        )

    def get_object(self):
        study = super().get_object()
        if self.request.user != study.author:
            redirect('study:list')
        return study


class StudyDeleteView(
    StudyChangeMixin, OnlyTeacherAuthorMixin, DeleteView
):
    template_name = 'study/edit.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **kwargs,
            form=StudyForm(
                instance=get_object_or_404(
                    Study,
                    pk=self.kwargs[self.pk_url_kwarg]
                )))

    def get_success_url(self):
        return reverse('study:list')


class ReviewCreateView(
    ReviewModelMixin, LoginRequiredMixin, ReviewFormMixin, CreateView
):
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.study = Study.objects.get(id=self.kwargs['study_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'study:detail', args=(self.kwargs['study_id'],)
        ) + '#reviews'


class ReviewUpdateView(
    OnlyAuthorMixin, ReviewURLParamMixin, ReviewFormMixin, UpdateView
):
    def post(self, request, *args, **kwargs):
        review = super().get_object()
        if review.edited is False:
            review.edited = True
            review.save()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('study:detail', args=(self.kwargs['study_id'],))


class ReviewDeleteView(
    OnlyAuthorMixin, ReviewURLParamMixin, DeleteView
):
    def get_success_url(self):
        return reverse('study:detail', args=(self.kwargs['study_id'],))


class CategoryListView(
    CategoryMixin, LoginRequiredMixin, ListView
):
    template_name = 'study/category_list.html'

    def get_queryset(self):
        return filtered_queryset(
            Category.objects, is_admin=self.request.user.is_staff
        )


class CategoryDetailView(
    CategoryChangeMixin, LoginRequiredMixin, DetailView
):
    template_name = 'study/category_detail.html'


class CategoryCreateView(
    CategoryFormMixin, OnlyStaffCanChange, CreateView
):
    model = Category

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('study:category_list')


class CategoryUpdateView(
    CategoryChangeMixin, CategoryFormMixin, OnlyStaffCanChange, UpdateView
):
    pass


class CategoryDeleteView(CategoryChangeMixin, OnlyStaffCanChange, DeleteView):
    template_name = 'study/category_edit.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **kwargs,
            form=CategoryForm(
                instance=get_object_or_404(
                    Category,
                    slug=self.kwargs[self.slug_url_kwarg]
                )
            )
        )


def add_documents_for_study(request, study_id):
    study = get_object_or_404(
        Study,
        id=study_id
    )
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            Document.objects.create(
                title=form.cleaned_data['title'],
                study=study,
                file=form.cleaned_data['file']
            )
            return redirect('study:detail', study_id)
    form = DocumentForm()
    return render(
        request,
        'study/add_documents.html',
        {
            'form': form,
            'study': study
        }
    )

pet/templates/study/add_documents.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}
  Добавление учебных материалов
{% endblock %}

{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card col-6 m-5">
      <div class="card-title">
        Загрузка файлов для '{{ study.name }}'
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Загрузить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

pet/templates/study/category_detail.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block content %}
  <div class="d-flex justify-content-center m-5">
    {% include 'includes/category_card.html' %}
  </div>
{% endblock %}

pet/templates/study/category_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  {% if 'create/' in request.path %}
    Добавление материала
  {% elif 'edit/' in request.path %}
    Редактирование материала
  {% else %}
    Удаление материала
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card">
      <div class="card-header">
        {% if 'create/' in request.path %}
          Добавление материала
        {% elif 'edit/' in request.path %}
          Редактирование материала
        {% else %}
          Удаление записи
        {% endif %}
        {% with form.instance as data %}
      </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% if not 'delete/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <h4>{{ data.name }}</h4>
              <p>{{ data.description }}</p>
              <p class="text-muted">{{ data.created }}</p>
              <h6 class="text-muted">{{ data.author.username }}</h6>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      {% endwith %}
    </div>
  </div>
{% endblock %}

pet/templates/study/category_list.html
{% extends 'base.html' %}

{% block title %}
  Категории
{% endblock %}

{% block content %}
  <h1 class="text-primary">
    Список всех доступных категорий:
  </h1>
  <div class="row mx-auto">
    {% for category in page_obj %}
      {% include 'includes/category_card.html' %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

pet/templates/study/detail.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}
  {{ study.title }}
{% endblock %}

{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card col-6 m-5">
      {% if study.image %}
        <img src="{{ study.image.url }}" height="100" width="100">
      {% endif %}
      <div class="card-body">
        <h2 class="card-title text-primary text-center">{{ study.name }}</h2><hr>
        <h6 class="card-subtitle text-danger">
          <small>
            {% if not study.is_published %}
              <p class="text-danger">Материал снят с публикации</p> 
            {% endif %}
          </small>
        </h6>
        <p class="card-text my-3">
          <span class="text-info">Описание курса:</span><br>
          {{ study.description }}<br>
          <small class="text-muted">от автора: {{ study.author.username }}</small><br>
        </p>
        {% if user == study.author %}
          <a href="{% url 'study:update' study.id %}" class="btn btn-info btn-sm text-white">Редактировать</a>
          <a href="{% url 'study:delete' study.id %}" class="btn btn-info btn-sm text-white">Удалить</a>
        {% endif %}
      </div>
        <div id="reviews" class="m-3 fs-3 text-info">
          Рейтинг: 
          {% with study.avg_rating as rating %}
            <span class="{% if rating >= 4 %}text-success{% elif 3 <= rating < 4 %}text-warning{% else %}text-danger{% endif %}">
              {{ rating }}
            </span>
          {% endwith %}
      </div>
      <div class="card-footer">
        {% for review in page_obj %}
          {% include 'includes/review_card.html' %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>
    </div>
  </div>
{% endblock %}

pet/templates/study/edit.html
{% extends 'base.html' %}

{% block title %}
  {% if 'create/' in request.path %}
    Добавление материала
  {% elif 'edit/' in request.path %}
    Редактирование материала
  {% else %}
    Удаление материала
  {% endif %}
{% endblock %}

{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card">
      <div class="card-header">
        {% if 'create/' in request.path %}
          Добавление материала
        {% elif 'edit/' in request.path %}
          Редактирование материала
        {% else %}
          Удаление записи
        {% endif %}
        {% with form.instance as data %}
      </div>
        <div class="card-body">
          {% if data.image %}
            <img src="{{ data.image.url }}">
          {% endif %}
          <form method="post">
            {% csrf_token %}
            {% if not 'delete/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <h4>{{ data.title }}</h4>
              <p>{{ data.description }}</p>
              <p class="text-muted">{{ data.created }}</p>
              <h6 class="text-muted">{{ data.author.username }}</h6>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      {% endwith %}
    </div>
  </div>
{% endblock %}

pet/templates/study/list.html
{% extends 'base.html' %}

{% block title %}
  Список предметов
{% endblock %}

{% block content %}
  <div class="row mx-auto">
    {% for study in page_obj %}
      {% include 'includes/study_card.html' %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

pet/templates/study/review_edit.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block title %}
  {% if 'create/' in request.path %}
    Добавление материала
  {% elif 'edit/' in request.path %}
    Редактирование материала
  {% else %}
    Удаление материала
  {% endif %}
  {% endblock %}
{% block content %}

  <div class="col d-flex justify-content-center">
    <div class="card">
      <div class="card-header">
        {% if 'create/' in request.path %}
              Добавление материала
            {% elif 'edit/' in request.path %}
              Редактирование материала
            {% else %}
              Удаление записи
            {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Создать комментарий" %}
        </form>
      </div>
      <!-- <div class="card-footer">
        <div class="text-danger">
          Внимание! Комментарий невозможно будет отредактировать
        </div>
      </div> -->
    </div>
  </div>
{% endblock %}