pet/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CategoryViewSet, ReviewViewSet, StudyViewSet

app_name = 'api'


v1_router = DefaultRouter()
v1_router.register(
    'study',
    StudyViewSet,
    basename='study'
)
v1_router.register(
    'category',
    CategoryViewSet,
    basename='category'
)
v1_router.register(
    r'study/(?P<study_id>\d+)/review',
    ReviewViewSet,
    basename='review'
)
urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('v1/', include(v1_router.urls))
]

pet/pet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from study import views
from study.forms import CustomUserForm

handler404 = 'tools.views.page_not_found'
handler500 = 'tools.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/logout/',
         views.CustomLogoutView.as_view(),
         name='custom_logout'),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration.html',
            form_class=CustomUserForm,
            success_url=reverse_lazy('study:list')
        ),
        name='registration'
    ),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('project_tools/', include('tools.urls', namespace='tools')),
    path('', include('study.urls', namespace='study')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/study/urls.py
from django.urls import path

from . import views


app_name = 'study'


urlpatterns = [
     path('',
          views.StudyListView.as_view(),
          name='list'),
    path('study/create/',
         views.StudyCreateView.as_view(),
         name='create'),
    path('study/detail/<int:study_id>/add_documents/',
         views.add_documents_for_study,
         name='download_documents'),
    path('study/detail/<int:study_id>/',
         views.StudyDetailView.as_view(),
         name='detail'),
    path('study/update/<int:study_id>/',
         views.StudyUpdateView.as_view(),
         name='update'),
    path('study/delete/<int:study_id>/',
         views.StudyDeleteView.as_view(),
         name='delete'),
    path('study/<int:study_id>/review/create/',
         views.ReviewCreateView.as_view(),
         name='review_create'),
    path('study/<int:study_id>/review/update/<int:review_id>/',
         views.ReviewUpdateView.as_view(),
         name='review_update'),
    path('study/<int:study_id>/review/delete/<int:review_id>/',
         views.ReviewDeleteView.as_view(),
         name='review_delete'),
    path('category/list/',
         views.CategoryListView.as_view(),
         name='category_list'),
    path('category/create/',
         views.CategoryCreateView.as_view(),
         name='category_create'),
    path('category/detail/<slug:category_slug>/',
         views.CategoryDetailView.as_view(),
         name='category_detail'),
    path('category/update/<slug:category_slug>/',
         views.CategoryUpdateView.as_view(),
         name='category_update'),
    path('category/delete/<slug:category_slug>/',
         views.CategoryDeleteView.as_view(),
         name='category_delete'),
]

pet/tools/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'tools'


urlpatterns = [
    path('about/',
         TemplateView.as_view(template_name='tools/about.html'),
         name='about'),
    path('rules/',
         TemplateView.as_view(template_name='tools/rules.html'),
         name='rules'),
]

pet/templates/includes/category_card.html
<div class="card col-3 m-2">
  <div class="card-header">
    {{ category.name }}
  </div>
  <div class="card-body">
    {{ category.created }}
  </div>
</div>

pet/templates/includes/footer.html
{% load django_bootstrap5 %}

<footer style="background: rgb(195, 188, 188)">
  <h6 class="text-muted text-center">
    <a href="https://vk.com/kspohodyaev" class="btn btn-info btn-sm mx-auto d-block text-white" style="background-color: rgb(50, 41, 41)">ССылка на автора проекта</a>
  </h6>
</footer>

pet/templates/includes/header.html
{% load static %}
{% load django_bootstrap5 %}

<header>
  <nav class="navbar navbar-light" style="background-color: rgb(50, 41, 41)">
    <div class="container">
      <a class="navbar-brand" href="{% url 'study:list' %}">
        <img src="{% static 'img/logo.png' %}" width="80" height="80">
        <small class="text-white fs-1 mx-2">KARTStudy</small>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <span class="row link-white">
          <ul class="nav nav-pills">
            <li class="nav-item mx-2">
              <button type="button" class="btn btn-outline-primary">
                <a class="nav-link" href="{% url 'tools:rules' %}">Правила</a>
              </button>
            </li>
            <li class="nav-item mx-2">
              <button type="button" class="btn btn-outline-primary">
                <a class="nav-link" href="{% url 'tools:about' %}">О нас</a>
              </button>
            </li>
            {% if user.is_authenticated and user.status == 'teacher' %}
              <li class="nav-item mx-2">
                <button type="button" class="btn btn-outline-primary">
                  <a href="{% url 'study:create' %}" class="nav-link">Создать учебный материал</a>
                </button>
              </li>
            {% endif %}
            {% if user.is_authenticated %}
              <li class="nav-item mx-2">
                <button type="button" class="btn btn-outline-primary">
                  <a class="nav-link" href="{% url 'custom_logout' %}">Выйти</a></button>
              </li> 
            {% else %}
              <li class="nav-item mx-2">
                <button type="button" class="btn btn-outline-primary">
                  <a href="{% url 'login' %}" class="text-decoration-none text-reset">Войти</a>
                </button>
              </li>
              <li class="nav-item mx-2">
                <button type="button" class="btn btn-outline-primary">
                  <a href="{% url 'registration' %}" class="text-decoration-none text-reset">Регистрация</a>
                </button>
              </li>
            {% endif %}
          </ul>
        </span>
      {% endwith %}
    </div>
  </nav>
</header>

pet/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

pet/templates/includes/profile_card.html
<div class="card col-5 m-5">
  <div class="card-body">
    <h4 class="card-title text-center">{{ profile.username }}</h4>
    <p class="card-text">
      Фамилия: {{ profile.first_name }}<br>
      Имя: {{ profile.last_name }}
    </p>
    <p>
      <a href="{% url 'profiles:detail' profile.username %}" class="btn btn-info btn-sm text-white">Подробнее</a>
    </p>
  </div>
</div>
  

pet/templates/includes/review_card.html
<div class="card my-2">
  {% if review.image %}
    <div class="m-1">
      <img src="{{ review.image.url }}"   height="auto" width="100%" alt="Изображение отзыва">
    </div>
  {% endif %}
  <div class="card-header">
    Отзыв пользователя {{ review.auhor }}
  </div>
  <div class="card-body">
    {% with review.mark as mark %}
      {% if mark > 3 %}
        <h4 class="text-success">Оценка: {{ review.mark }}</h4>
      {% elif mark > 2 and mark < 4 %}
        <h4 class="text-warning">Оценка: {{ review.mark }}</h4>
      {% else %}
        <h4 class="text-danger">Оценка: {{ review.mark }}</h4>
      {% endif %}
    {% endwith %}
    <div class="my-3">
      {{ review.text }}<br>
      {% if review.edited %}
        <small class="text-secondary">Комментарий был отредактирован</small>
      {% endif %}
    </div>
    {% if user.is_staff %}
      <a href="{% url 'study:review_update' review.id review.study.id %}" class="btn btn-outline-info btn-sm text-info">Редактировать</a>
      <a href="{% url 'study:review_delete' review.id review.study.id %}" class="btn btn-outline-info btn-sm text-info">Удалить</a>
    {% endif %}
  </div>
  <div class="card-footer">
    <p class="text-muted">
      {{ review.created }}
    </p>
  </div>
</div>

pet/templates/includes/study_card.html
<div class="card col-5 m-5">
  {% if study.image %}
    <img src="{{ study.image.url }}" height="100">
  {% endif %}
  <div class="card-body">
    <h4 class="card-title text-center text-primary">{{ study.name }}</h4><hr>
    <h6 class="card-subtitle text-danger">
      <small>
        {% if not study.is_published %}
          <p class="text-danger">Курс снят с публикации</p>
        {% endif %}
      </small>
    </h6>
    <div class="card-text">
      <p>Короткое название: <small class="text-primary">{{ study.slug }}</small></p>
      <small>Создано: {{ study.created }}</small><br>
      <small>Дата последнего редактирования: {{ study.edit }}</small><br>
      <small class="text-muted">от автора: {{ study.author.username }}</small>
    </div>
    <div class="card-text">
      <div class="text-info">Описание</div>
      {{ study.description|truncatewords:10 }}
    </div>
    <hr>
    <p class="text-info">
      {% if not study.rating %}
        Оценок нет
      {% else %}
        Рейтинг: {{ study.rating }}
      {% endif %}
    </p>
    <a href="{% url 'study:detail' study.id %}" class="btn btn-info btn-sm m-1 text-white">Читать полностью:</a>
    <a href="{% url 'study:review_create' study.id %}" class="btn btn-info btn-sm m-1 text-white">Написать отзыв:</a>
  </div>
</div>